# Site/SEO settings
email: okimoniart@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Okimoni
title: Okimoni Art
description: >
  Paintings portfolio of Okimoni
url: https://okimoni.github.io/
# twitter_username: thomasvaeth
default_img: /assets/images/profile-0.jpeg
social:
  # - name: twitter
  #   url: https://twitter.com/thomasvaeth
  - name: instagram
    url: https://www.instagram.com/0kimoni.art/
  # - name: facebook
  #   url: https://www.facebook.com/carla.gherci
  # - name: linkedin
  #   url: https://www.linkedin.com/in/thomasvaeth/
  # - name: github
  #   url: https://github.com/samesies
  # - name: codepen
  #   url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/contact.jpg
formcarry: https://formcarry.com/s/kiPo-zCStN

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Okimoni
    bio: Okimoni was born in Marseille, France. She studied art in London and now finds her inspiration in Lisbon, Portugal.
    url: https://www.instagram.com/0kimoni.art/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Okimoni'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
